### ISSUE TITLE
Create a folder/directory named myFirstFolder in this repository

### ISSUE THREAD

**Issue by mithunrajarackal** [elvinsara/computerBasics#1]
Hi @elvinsara 

### Ninakkulla new task.

Create a folder/directory with name `myFirstFolder` in this repository.
Within this `myFirstFolder` directory add two files.

File 1: A text file containing your favourite movies - 5 of them, each in one line. Give the file a suitable name. Example: `favouriteMoviesList.txt`.

File 2: A picture of One Direction band members or logo
Hint: Use Firefox to browse images of One Direction. Download one of the image by `Right click` on the image followed by clicking `Save image as` from the menu that appeared.
Use `cp` command to copy file from one directory to another. Use `ls` command to verify whether the file is actually copied to the target directory.
Eg: `cp /home/elvin/Downloads/a.txt /home/elvin/Documents/.` command will copy the file `a.txt` from the directory `/home/elvin/Downloads` to `/home/elvin/Documents`. After submitting the copy command the file `a.txt` will be present in the `/home/elvin/Documents` folder. 

Suggestion:
Create the directory `myFirstFolder` and then try to commit and push the changes first. Then once the changes are pushed add the two files mentioned above to this directory. Commit again and push the new changes.
Commands for pushing changes to the repository
```
git status ---> command to check status of files before pushing
git add <insert-file-name-or-directory-here> ---> command to add a file before committing changes
git commit -m `<insert-commit-message-here>` ---> actual commit command
git push origin main ---> command to push the changes in your local system to the github repository
```

All the best... :grin:

**Comment by elvinsara** [comment]
completed task
